executable     = run_dch.sh
arguments      = DCH_tauFR $(year) 8
output         = logs/dch_tauFR_$(year).out
error          = logs/dch_tauFR_$(year).err
log            = logs/dch_tauFR_$(year).log
request_cpus   = 8
request_memory = 16000
request_disk   = 2000000
+JobFlavour    = "tomorrow"
use_x509userproxy = true
x509userproxy  = /afs/cern.ch/user/a/atahmad/.grid_proxy/x509up.pem

queue year in (2016preVFP, 2016postVFP, 2017, 2018)
