executable     = run_dch_chunk.sh
arguments      = DCH_tight $(year) $(idx) $(chunkidx)
output         = logs/dch_tight_chunk_$(year)_$(idx)_$(chunkidx).out
error          = logs/dch_tight_chunk_$(year)_$(idx)_$(chunkidx).err
log            = logs/dch_tight_chunk_$(year)_$(idx)_$(chunkidx).log
request_cpus   = 1
request_memory = 1000
request_disk   = 500000
+JobFlavour    = "workday"
use_x509userproxy = true
x509userproxy  = /afs/cern.ch/user/a/atahmad/.grid_proxy/x509up.pem

queue year,idx,chunkidx from chunklist.txt
