executable     = run_derive_perfile.sh
arguments      = $(year) $(idx)
output         = logs/derive_recoil_$(year)_$(idx).out
error          = logs/derive_recoil_$(year)_$(idx).err
log            = logs/derive_recoil_$(year)_$(idx).log
request_cpus   = 1
request_memory = 3000
request_disk   = 2000000
+JobFlavour    = "workday"
use_x509userproxy = true
x509userproxy  = /afs/cern.ch/user/a/atahmad/.grid_proxy/x509up.pem

queue year,idx from ../../batch/filelist.txt
